import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Bungee_Shade } from "next/font/google";

import { cn } from "@/lib/utils";
import Layout from "@/components/shared/layout";
import "./globals.css";

const bungee = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const runtime = "edge";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "svgBg font-sans antialiased dark h-dvh",
          bungee.variable,
          inter.variable
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
