import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Bungee_Shade } from "next/font/google";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import Layout from "@/components/shared/layout";
import "./globals.css";

const bungee = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});

const inter = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "svgBg font-sans antialiased dark h-dvh",
          bungee.variable,
          inter.variable
        )}
      >
        <Layout>{children}</Layout>
        <Toaster />
      </body>
    </html>
  );
}
